name: Deployment of Spring boot Application

on: 
    push:
        branches: [ "12-image-creation-with-spring-boot-artifact" ]


    # workflow_dispatch:
    #   inputs:
    #     appVersion: 
    #       description: 'Input Version'
    #     versionValue: 
    #       description: 'Input Values'

env: 
     REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
     IMAGE_TAG: $$ {{ secrets.IMG_TAG_SB_APP }}


jobs:
    deploy-application:
        name: spring boot application deployment
        runs-on: ubuntu-latest


        steps: 
            - name: Docker Login
              uses: docker/login-action@v3.0.0
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Check Login Successfull or not
              run: |
                  docker pull ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG}}
                  echo "Login to Dockerhub is Successfull"
            

            
        
