name: Build, Test and Generate Artifact for the Spring Boot Application

on: 
  push:
    branches: [ "9-ci-workflow-for-spring-boot-app" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
        
            - name: SetUp JDK 
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Change directory to where pom.xml is located
              run: cd spring-boot-app
          

            - name: Maven build
              run: mvn -f spring-boot-app/pom.xml clean package
              


            